apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-configmaps-demo
spec:
  selector:
    matchLabels:
      app: springboot-configmaps-demo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springboot-configmaps-demo
    spec:
      containers:
      - image: rajapiconnect1/spring-boot-configmaps-demo 
        name: springboot-configmaps-demo
        imagePullPolicy: Always
        ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
        envFrom:
            - configMapRef:
                name: greeting-prefix
      restartPolicy: Always
      