kind: Service
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  name: springboot-configmaps-demo
  labels:
    app: springboot-configmaps-demo
    app.kubernetes.io/component: springboot-configmaps-demo
    app.kubernetes.io/instance: springboot-configmaps-demo
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 9090
      targetPort: 9080
    - name: 8443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: 8778-tcp
      protocol: TCP
      port: 10080
      targetPort: 8080
  selector:
    app: springboot-configmaps-demo
  type: ClusterIP
  sessionAffinity: None
